### ISSUE TITLE
Consider using styles for styling the button.

### ISSUE THREAD

**Issue by evant** [willowtreeapps/sign-in-with-apple-button-android#24]
Noticed, you had a `SignInTheme` enum. The standard way to do this on android is by defining a few styles. Ex:

```
<style name="SignInWithAppleButton.White>
    <item name="android:textColor">@color/black</item>
    <item name="android:background">@drawable/white</item>
    <item name="appleButton_icon">@drawable/ic_apple_logo_black</item>
</style>
```
and then set it on the view with
```
<com.willowtreeapps.signinwithapplebutton.view.SignInWithAppleButton
     style="@style/SignInWithAppleButton.White"
```

**Comment by kconner** [comment]
According to docs, when you specify a style with `style=`, it applies only to that very element, but I need to style a child view too (a TextView). If you specify it with `theme=`, then it applies to all children, which works, but it means there's a possibility the library consumer will use it the wrong way and not get the expected style. What do you think is the right course of action?

**Comment by evant** [comment]
App compat backports themes so I wouldn't worry about that, as for styles not applying to children, I think in this case it might make sense to manually set the attributes on the child, you can think of the button as a black box, where the user of the lib doesn't have to know it's a FrameLayout and not a button. 

For example, for android:textColor you can add it to your `declare-stylable`
```xml
<declare-styleable name="SignInWithAppleButton">
    <attr name="android:textColor"/>
</declare-styleable>
```
and then in your view do
```kotlin
textView.setTextColor(attributes.getColorStateList(R.styleable.SignInWithAppleButton_android_textColor))
```

Obviously this will be a pain if you want to forward a lot of attributes, but for a limited subset it should work reasonably well.
