### ISSUE TITLE
Release 0.3 not available in Maven

### ISSUE THREAD

**Issue by john-mejia** [willowtreeapps/sign-in-with-apple-button-android#56]
Maven only shows releases 0.1 and 0.2, making it so we can't update to 0.3

https://mvnrepository.com/artifact/com.willowtreeapps/signinwithapplebutton

**Comment by john-mejia** [comment]
@jordan-fallon-willowtree - do you know when we can expect the 0.3 release in maven?

**Comment by matteinn** [comment]
^ any updates on this?

**Comment by jordan-fallon-willowtree** [comment]
We're working on getting 0.3 deployed to maven and will close this out when it's available. Thanks!

**Comment by jordan-fallon-willowtree** [comment]
https://search.maven.org/artifact/com.willowtreeapps/signinwithapplebutton/0.3/aar
