### ISSUE TITLE
Dependency version 0.4 does not work

### ISSUE THREAD

**Issue by padwekar** [willowtreeapps/sign-in-with-apple-button-android#62]
When trying to use v4 version of this library. I am getting the following error :
ERROR: Failed to resolve: com.willowtreeapps:signinwithapplebutton:0.4

But v3 version is recognized properly.     
implementation 'com.willowtreeapps:signinwithapplebutton:0.3' works 

Is the v4 version ready? if not why the dependency for v4 version is given in the documentation?

**Comment by evant** [comment]
You are right, version 4 does not appear to be published https://search.maven.org/search?q=g:com.willowtreeapps%20AND%20a:signinwithapplebutton

**Comment by smithks** [comment]
We got a bit ahead of ourselves with updating documentation, sorry @padwekar! Version .3 is the latest.

**Comment by padwekar** [comment]
Thanks for your quick response. I will use version .3. You guys are doing a great job.
