### ISSUE TITLE
callback won't work and view doesn't close

### ISSUE THREAD

**Issue by simonesummo** [willowtreeapps/sign-in-with-apple-button-android#68]
I'm getting the error chromium: [INFO:CONSOLE(169)] "Scripts may close only the windows that were opened by them."

**Comment by Aye-Myat-Mon** [comment]
same here. have you found any solution?

**Comment by Aye-Myat-Mon** [comment]
same here! have you found any solution?

**Comment by jcchikikomori** [comment]
> same here! have you found any solution?

I found the culprit.
Apple returns the redirect URL with one specific change.
The `/handler` was replacing into a `/result` which is it became `false` on the `url.toString().contains(...)` condition
Check my latest fork.
